export const blogs = {
  GET_BLOGS: "GET_BLOGS",
  GET_BLOGS_SUCCESS: "GET_BLOGS_SUCCESS",
  GET_BLOGS_LOADING: "GET_BLOGS_LOADING",
  GET_BLOGS_FAILURE: "GET_BLOGS_FAILURE",

  GET_BLOG_BY_ID: "GET_BLOG_BY_ID",
  GET_BLOG_BY_ID_SUCCESS: "GET_BLOG_BY_ID_SUCCESS",
  GET_BLOG_BY_ID_LOADING: "GET_BLOG_BY_ID_LOADING",
  GET_BLOG_BY_ID_FAILURE: "GET_BLOG_BY_ID_FAILURE",

  CREATE_BLOG: "CREATE_BLOG",
  CREATE_BLOG_SUCCESS: "CREATE_BLOG_SUCCESS",
  CREATE_BLOG_LOADING: "CREATE_BLOG_LOADING",
  CREATE_BLOG_FAILURE: "CREATE_BLOG_FAILURE",
  CREATE_BLOG_RESET: "CREATE_BLOG_RESET",

  UPDATE_BLOG: "UPDATE_BLOG",
  UPDATE_BLOG_SUCCESS: "UPDATE_BLOG_SUCCESS",
  UPDATE_BLOG_LOADING: "UPDATE_BLOG_LOADING",
  UPDATE_BLOG_FAILURE: "UPDATE_BLOG_FAILURE",
  UPDATE_BLOG_RESET: "UPDATE_BLOG_RESET",

  DELETE_BLOG: "DELETE_BLOG",
  DELETE_BLOG_SUCCESS: "DELETE_BLOG_SUCCESS",
  DELETE_BLOG_LOADING: "DELETE_BLOG_LOADING",
  DELETE_BLOG_FAILURE: "DELETE_BLOG_FAILURE",
  DELETE_BLOG_RESET: "DELETE_BLOG_RESET",
};
