export const works = {
  GET_WORKS: "GET_WORKS",
  GET_WORKS_SUCCESS: "GET_WORKS_SUCCESS",
  GET_WORKS_LOADING: "GET_WORKS_LOADING",
  GET_WORKS_FAILURE: "GET_WORKS_FAILURE",

  GET_WORK_BY_ID: "GET_WORK_BY_ID",
  GET_WORK_BY_ID_SUCCESS: "GET_WORK_BY_ID_SUCCESS",
  GET_WORK_BY_ID_LOADING: "GET_WORK_BY_ID_LOADING",
  GET_WORK_BY_ID_FAILURE: "GET_WORK_BY_ID_FAILURE",

  CREATE_WORK: "CREATE_WORK",
  CREATE_WORK_SUCCESS: "CREATE_WORK_SUCCESS",
  CREATE_WORK_LOADING: "CREATE_WORK_LOADING",
  CREATE_WORK_FAILURE: "CREATE_WORK_FAILURE",
  CREATE_WORK_RESET: "CREATE_WORK_RESET",

  UPDATE_WORK: "UPDATE_WORK",
  UPDATE_WORK_SUCCESS: "UPDATE_WORK_SUCCESS",
  UPDATE_WORK_LOADING: "UPDATE_WORK_LOADING",
  UPDATE_WORK_FAILURE: "UPDATE_WORK_FAILURE",
  UPDATE_WORK_RESET: "UPDATE_WORK_RESET",

  DELETE_WORK: "DELETE_WORK",
  DELETE_WORK_SUCCESS: "DELETE_WORK_SUCCESS",
  DELETE_WORK_LOADING: "DELETE_WORK_LOADING",
  DELETE_WORK_FAILURE: "DELETE_WORK_FAILURE",
  DELETE_WORK_RESET: "DELETE_WORK_RESET",
};
